### ISSUE TITLE
Making Triplex MySQL compatible

### ISSUE THREAD

**Issue by maxmarcon** [ateliware/triplex#52]
Hi everyone,

we started using Elixir for a new project with my team recently, and we are quite excited :)
We also needed multi-tenancy, and we liked Triplex approach to it. However, we also wanted to keep using our good old MySQL database. Because Triplex does not currently support MySQL, we extended it with MySQL support. Our approach works as follows:

1) We added a mix task (`triplex.init.tenant `) that generates a migration to create a `tenant` table in the main ecto Repo's database. This table will contain a list of all registered tenants.
2) When using the MySQL ecto adapter, calls to `Triplex.create` and `Triplex.drop` will add/remove entries from the `tenannts` table and create/drop the respective MySQL databases. Calls to `Triplex.rename` will raise an exception because MySQL does not support renaming of databases
3) Everything else works as in the PostgreSQL case by prefixing table names with the name of the tenant (and thus the database).

This is our fork: https://github.com/maxmarcon/triplex-mysql

It's still rough at the edges, we will at the very minimum need to update your tests, but I was wondering if you guys are interested in eventually including our changes into your project (after a code review process, of course).

Thanks,
Max

**Comment by kelvinst** [comment]
@maxmarcon we surely are interested in contributions! And adding support to mysql was in our plans already. Can you open a PR with your changes?

**Comment by maxmarcon** [comment]
There you go. Looking forward to your comments.

**Comment by richardriman** [comment]
+1 for mysql support

**Comment by mgiacomini** [comment]
The PR #53 was merged into master! We are looking forward to release a new version. Thanks for your contributions  :)
