### ISSUE TITLE
cast_assoc is not saving prefix.

### ISSUE THREAD

**Issue by kapilpipaliya** [ateliware/triplex#54]
company has many contacts i want to save contact via cast_assoc function

```
%Company{}
           |> Repo.preload([:contacts], prefix: tenant)
           |> Company.changeset(company_params,tenant)
           |> Ecto.Changeset.cast_assoc(:contacts, prefix: tenant)
           |> Repo.insert(prefix: tenant)
```

last line gives error. `(undefined_table): relation "contacts" does not exist`
Please Help.

**Comment by kelvinst** [comment]
@kapilpipaliya I don't think `:prefix` is a valid option to `cast_assoc`: https://hexdocs.pm/ecto/Ecto.Changeset.html#cast_assoc/3-options

Anyways, that should not be the problem. Can you please give us the ecto version you're using? I remember I got something like that too and opened a PR to fix it on Ecto and it's merged and released right now.

**Comment by kelvinst** [comment]
Forget about it, the fix I did there had nothing to do with this. But still, just send the version and I will check it out.

**Comment by kapilpipaliya** [comment]
I am using:
`{:ecto, "~> 2.2"},`

**Comment by mgiacomini** [comment]
i'm closing this issue because cast_assoc/3 doesn't support the prefix option.
