### ISSUE TITLE
Ecto 3 Support

### ISSUE THREAD

**Issue by kapilpipaliya** [ateliware/triplex#59]
Please Make this library working with ecto 3.
I updated to ecto 3,
but when i run the migration with `Triplex.create(..) in Repo.transaction()`,this line:
https://github.com/ateliware/triplex/blob/master/lib/triplex.ex#L263
gives error: 'schema not found'
but it created schema before successfully with `create schema ..`;

other notes:
`source_repo_priv` function has moved to https://github.com/elixir-ecto/ecto_sql/blob/8c7acebea4d04b7e541441b678be62c820c88e22/lib/mix/ecto_sql.ex#L88

**Comment by mgiacomini** [comment]
@kapilpipaliya tks for report the issue. I haven't tested triplex with ecto3 yet, but will work on this

**Comment by abarr** [comment]
Hi @mgiacomini, do you need some help with this? Are you going to retain support for ecto 2.*?

**Comment by abarr** [comment]
@kapilpipaliya I have made a pull request after updating Triplex to support Ecto 3.0.1, although it needs to be reviewed and checked by @mgiacomini it might allow you to keep working on your development.

Andrew

**Comment by mgiacomini** [comment]
@abarr thanks for your PR. After talking with @kelvinst, we want release soon a new version of triplex with ecto 3 support and some refactors in the plugs part. The support for ecto 2 probably will be kept only in the triplex v1.2.

**Comment by keithpitty** [comment]
> @abarr thanks for your PR. After talking with @kelvinst, we want release soon a new version of triplex with ecto 3 support and some refactors in the plugs part. The support for ecto 2 probably will be kept only in the triplex v1.*.

@mgiacomini I'm keen to upgrade my app to Phoenix 1.4.0, which depends upon Ecto 3. What's the latest on this issue? Is there any way I can help?

**Comment by rwngallego** [comment]
This is the referenced PR from @abarr: https://github.com/ateliware/triplex/pull/61

It still needs the approval from @mgiacomini

**Comment by mgiacomini** [comment]
Sorry about the late response, guys. @kelvinst is working on the upgrade to ecto 3.

**Comment by kelvinst** [comment]
Closed by #61
