### ISSUE TITLE
Investigate the dynamic repo's idea

### ISSUE THREAD

**Issue by kelvinst** [ateliware/triplex#71]
This is the article about it https://underjord.io/ecto-multi-tenancy-dynamic-repos-part-1-getting-started.html

**Comment by abarr** [comment]
Hi Kelvin,

I think that Underjord eventually came around to the idea of `prefix` as a less complex solution https://underjord.io/ecto-multi-tenancy-prefixes-part-3.html

Are you still thinking about this?

Andrew

**Comment by kelvinst** [comment]
Well, the whole point of this issue is that I didn't have time to dig on it deeply. I was thinking that maybe if we used this dynamic repo's, instead of having to remember to send the `prefix` opt every time a query is done, the dynamic repo would get it for us.

But as you pointed out, that ended up even more complex for underjord. Let's close this issue and maybe think of a way to do that in the future, IDK
